Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 153, in blog_list
    return render(request, 'core/blog_list.html', {'posts': posts})
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'widthratio'
"GET /blog/ HTTP/1.1" 500 225281
Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 153, in blog_list
    return render(request, 'core/blog_list.html', {'posts': posts})
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'widthratio'
"GET /blog/ HTTP/1.1" 500 225281
Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
KeyError: 'math_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 153, in blog_list
    return render(request, 'core/blog_list.html', {'posts': posts})
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'math_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
"GET /blog/ HTTP/1.1" 500 187661
Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
KeyError: 'math_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 153, in blog_list
    return render(request, 'core/blog_list.html', {'posts': posts})
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'math_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
"GET /blog/ HTTP/1.1" 500 187661
Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
KeyError: 'math_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 153, in blog_list
    return render(request, 'core/blog_list.html', {'posts': posts})
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'math_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
"GET /blog/ HTTP/1.1" 500 187661
Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
KeyError: 'math_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 153, in blog_list
    return render(request, 'core/blog_list.html', {'posts': posts})
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'math_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
"GET /blog/ HTTP/1.1" 500 187661
Not Found: /blog/new/
"GET /blog/new/ HTTP/1.1" 404 4445
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "dpg-d0vlo60gjchc739to0pg-a.singapore-postgres.render.com" (18.142.152.125), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 19, in home
    return render(request, 'core/home.html')
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 320, in render
    match = condition.eval(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[bit]
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "dpg-d0vlo60gjchc739to0pg-a.singapore-postgres.render.com" (18.142.152.125), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

"GET / HTTP/1.1" 500 301257
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5777
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "dpg-d0vlo60gjchc739to0pg-a.singapore-postgres.render.com" (18.142.152.125), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 19, in home
    return render(request, 'core/home.html')
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 320, in render
    match = condition.eval(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[bit]
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor = self.connection.cursor()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\db\backends\postgresql\base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "dpg-d0vlo60gjchc739to0pg-a.singapore-postgres.render.com" (18.142.152.125), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

"GET /static/images/favicon.png HTTP/1.1" 404 1868
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
KeyError: "['blog_list',"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 19, in home
    return render(request, 'core/home.html')
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['blog_list',' from '['blog_list','
"GET / HTTP/1.1" 500 227561
Internal Server Error: /blog/
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
KeyError: "['blog_list',"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 153, in blog_list
    return render(request, 'core/blog_list.html', {'posts': posts})
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['blog_list',' from '['blog_list','
"GET /blog/ HTTP/1.1" 500 229664
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
KeyError: "['blog_list',"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 19, in home
    return render(request, 'core/home.html')
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['blog_list',' from '['blog_list','
"GET / HTTP/1.1" 500 227219
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
KeyError: "['blog_list',"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 19, in home
    return render(request, 'core/home.html')
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['blog_list',' from '['blog_list','
"GET / HTTP/1.1" 500 227219
"GET /static/images/favicon.png HTTP/1.1" 404 1868
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Not Found: /l
"GET /l HTTP/1.1" 404 5747
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5777
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
"GET /static/images/favicon.png HTTP/1.1" 404 1868
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5777
"GET /static/images/favicon.png HTTP/1.1" 404 1868
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Method Not Allowed (GET): /logout/
Method Not Allowed: /logout/
"GET /logout/ HTTP/1.1" 405 0
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\core\views.py", line 19, in home
    return render(request, 'core/home.html')
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'logout' not found. 'logout' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 165830
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'provider_login_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\rahul\Desktop\black_box\villen\venv\lib\site-packages\django\template\base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 97: 'provider_login_url', expected 'endblock'. Did you forget to register or load this tag?
"GET /login/ HTTP/1.1" 500 183327
"GET /static/images/favicon.png HTTP/1.1" 404 1868
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 6078
Internal Server Error: /tools/tool/1/
Traceback (most recent call last):
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Desktop/7may/web/tools/views.py", line 24, in tool_detail
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg'] or 0
                                       ^^^^^^
NameError: name 'models' is not defined
"GET /tools/tool/1/ HTTP/1.1" 500 74556
Not Found: /favicon.ico
Internal Server Error: /tools/tool/1/
Traceback (most recent call last):
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Desktop/7may/web/tools/views.py", line 25, in tool_detail
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg'] or 0
                                       ^^^^^^^^^^
AttributeError: module 'tools.models' has no attribute 'Avg'
"GET /tools/tool/1/ HTTP/1.1" 500 74698
Internal Server Error: /tools/tool/1/
Traceback (most recent call last):
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Desktop/7may/web/tools/views.py", line 25, in tool_detail
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg'] or 0
                                       ^^^^^^^^^^
AttributeError: module 'tools.models' has no attribute 'Avg'
"GET /tools/tool/1/ HTTP/1.1" 500 74698
Internal Server Error: /tools/tool/1/
Traceback (most recent call last):
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Desktop/7may/web/tools/views.py", line 25, in tool_detail
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg'] or 0
                                       ^^^^^^^^^^
AttributeError: module 'tools.models' has no attribute 'Avg'
"GET /tools/tool/1/ HTTP/1.1" 500 74698
Internal Server Error: /tools/tool/1/
Traceback (most recent call last):
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Desktop/7may/web/tools/views.py", line 25, in tool_detail
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg'] or 0
                                       ^^^^^^^^^^
AttributeError: module 'tools.models' has no attribute 'Avg'
"GET /tools/tool/1/ HTTP/1.1" 500 74698
Internal Server Error: /tools/tool/1/
Traceback (most recent call last):
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Desktop/7may/web/tools/views.py", line 26, in tool_detail
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg'] or 0
                                       ^^^^^^
NameError: name 'models' is not defined
"GET /tools/tool/1/ HTTP/1.1" 500 74556
Internal Server Error: /tools/tool/1/
Traceback (most recent call last):
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Desktop/7may/web/tools/views.py", line 26, in tool_detail
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg'] or 0
                                       ^^^^^^
NameError: name 'models' is not defined
"GET /tools/tool/1/ HTTP/1.1" 500 74556
Internal Server Error: /tools/tool/1/
Traceback (most recent call last):
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Desktop/7may/web/myenv/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/kali/Desktop/7may/web/tools/views.py", line 26, in tool_detail
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg'] or 0
                                       ^^^^^^
NameError: name 'models' is not defined
"GET /tools/tool/1/ HTTP/1.1" 500 74556
Not Found: /favicon.ico
